import React from "react";
import { motion } from "framer-motion";
import { Flex, useColorMode } from "@chakra-ui/react";
import Head from "next/head";
import Navbar from "../../components/Navbar";
import Feed from "../../components/Feed";
import ProfileComponent from "../../components/ProfileComponent";

const UserProfile = () => {
  const { colorMode } = useColorMode();
  return (
    <motion.div
      style={{
        minHeight: "100vh",
        width: "100%",
        backgroundColor: colorMode === "light" ? "#dbe0e6" : "#030303",
      }}
    >
      <Head>
        <title>PictureSh - IdiotBoi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isProfile={true} />
      <Flex
        paddingLeft="25px"
        paddingRight="10px"
        flexDirection="column"
        marginTop="50px"
      >
        <ProfileComponent />
        <Feed isProfile={true} />
      </Flex>
    </motion.div>
  );
};

export default UserProfile;
