import React from "react";
import { motion } from "framer-motion";
import { useColorMode } from "@chakra-ui/react";
import Navbar from "../../components/Navbar";
import Head from "next/head";
import ImageDetailsComponent from "../../components/ImageDetailsComponent";
import variants from "../../utils/variants";

const ImageDetails = () => {
  const { colorMode } = useColorMode();
  return (
    <motion.div
      variants={variants}
      initial="hidden"
      animate="enter"
      exit="exit"
      transition={{ type: "linear" }}
      style={{
        minHeight: "100vh",
        width: "100%",
        backgroundColor: colorMode === "light" ? "#f9f9f9" : "#030303",
      }}
    >
      <Head>
        <title>PictureSh - This is a nice image</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isSingleImage={true} />
      <ImageDetailsComponent />
    </motion.div>
  );
};

export default ImageDetails;
