import { Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>PictureSh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading fontFamily='"Work Sans", sans-serif'>PictureSh</Heading>
    </div>
  );
};

export default Home;
